spring.application.name=wsrcitamedica
server.servlet.context-path=/cita/medica/api
spring.profiles.active=dev

#Configuración común
spring.sql.init.mode=never
spring.jpa.open-in-view=false

spring.jackson.time-zone=America/Lima
spring.mvc.timezone=America/Lima
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.jhontruse.wsrcitamedica.controller
springdoc.paths-to-match=/**
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
