spring.datasource.url=jdbc:mysql://localhost:3306/DB_CITA_MEDICA?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

# LOGGING
logging.level.root=INFO
logging.level.com.pe.intranet.wsschool=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.com.example=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.file.path=/Users/jhontrujilloserrano/developer/logs/wsrCitaMedica/
logging.file.name=wsrCitaMedica-dev

# Ver SQL queries en desarrollo
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

